{% set version = "1.1.5" %}

package:
  name: alsa-lib
  version: {{ version }}

source:
  url: ftp://ftp.alsa-project.org/pub/lib/alsa-lib-{{ version }}.tar.bz2
  sha256: f4f68ad3c6da36b0b5241ac3c798a7a71e0e97d51f972e9f723b3f20a9650ae6

build:
  number: 1000
  skip: True  # [not linux]

requirements:
  build:
    - make
    - autoconf
    - automake
    - libtool
    - {{ compiler('c') }}
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libasound$SHLIB_EXT

about:
  home: http://www.alsa-project.org/main/index.php/Main_Page
  license: LGPL v2.1
  license_family: GPL
  license_file: COPYING
  summary: 'Advanced Linux Sound Architecture'

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
