{% set version = "1.2.6.1" %}

package:
  name: alsa-lib
  version: {{ version }}

source:
  url: https://www.alsa-project.org/files/pub/lib/alsa-lib-{{ version }}.tar.bz2
  sha256: ad582993d52cdb5fb159a0beab60a6ac57eab0cc1bdf85dc4db6d6197f02333f

build:
  number: 0
  skip: True  # [not linux]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=alsa
    - {{ pin_subpackage("alsa-lib", max_pin="x.x.x") }}

requirements:
  build:
    - make
    - autoconf
    - automake
    - libtool
    - {{ compiler('c') }}
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libasound$SHLIB_EXT

about:
  home: http://www.alsa-project.org/main/index.php/Main_Page
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'Advanced Linux Sound Architecture'

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
