{% set version = "1.2.7.2" %}

package:
  name: alsa-lib
  version: {{ version }}

source:
  url: https://github.com/alsa-project/alsa-lib/archive/v{{ version }}.tar.gz
  sha256: 2ed6d908120beb4a91c2271b01489181b28dc9f35f32229ef83bcd5ac8817654

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=alsa
    - {{ pin_subpackage("alsa-lib", max_pin="x.x.x") }}

requirements:
  build:
    - make
    - autoconf
    - automake
    - libtool
    - {{ compiler('c') }}
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libasound$SHLIB_EXT

about:
  home: http://www.alsa-project.org/main/index.php/Main_Page
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: COPYING
  summary: Advanced Linux Sound Architecture

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
    - ryanvolz
