{% set version = "1.2.3.2" %}

package:
  name: alsa-lib
  version: {{ version }}

source:
  url: https://github.com/alsa-project/alsa-lib/archive/v{{ version }}.tar.gz
  sha256: 406eec09aac2c4a34d847cc5f75ba8e3830815471bef50efdd52944d2e53ee59

build:
  number: 0
  skip: True  # [not linux]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=alsa
    - {{ pin_subpackage("alsa-lib", max_pin="x.x.x") }}

requirements:
  build:
    - make
    - autoconf
    - automake
    - libtool
    - {{ compiler('c') }}
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libasound$SHLIB_EXT

about:
  home: http://www.alsa-project.org/main/index.php/Main_Page
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'Advanced Linux Sound Architecture'

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
    - ryanvolz
