appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: YlDBeIpv9nCDN8fGCPRk5PN1TFlMXijH70nDPJV+9drcrd2EB7rQZimkCOShvrcnX/1j2sUZSqkMEfESa6vz64KKW0rcMaCm7DUpw5OPvSDbAkc8FMv+8TN+5Lukc2yUmwjjL9z3bVZCg2ZrPbTHVq/ERPX0HYjKvTRCl3speFHelipJAAj5xQbKdit90SoprFNGusMj2oudcohjnMs6vQJ8U52W6hH1EyqdLn/FR38Ln4dmzqN5U/omsAAHbuh+b9/7ZACniOjuPvULOQyQQG3679o6eH0N1KY4ikcr1nUsNOsd7e3RxsRzAwUB0Bm1HmJxLbYz31CUlQcSLEREU5yBChsbyUy6hGvkyUpwkGhGrC+r2m13K0ApBpkt07zqTV4ISgwLBUWUnXxxXWu5sOQPfjc3hr874YsnuDUwhb0nYtQuDUGVdmgOOiYaEjzIw1aQiGrQnKxE27mIpiFUs5CmGi9UI8tNcMVyPET989eaADk9xqJ99ae4uxGjmN0IPJbONjfE9YT9yhjMbTB88f5Q6WyfkobGYXdwTTp4sLRg1+PizfmsD/a+N2JO51FmdE+2FjFKYAOBv2E/CaKYAfLcV/R8I7Y6mtYmVz3JsA99zPfHL187yeEEaV1/mgOwh/Ia+IRiHi74RhS5CAurjRfbIYVNu1rvKjr8jf/3skY=}
conda_forge_output_validation: true
