travis:
  secure:
    BINSTAR_TOKEN: DwxM2L+5UnKHcXkk+fGB7+D/X4hfRO/U9SNp1nq8uUhwd/ePnQ25pkoBsg2bMC2eHjZ4+B8fFcJ3tCnZwjVkT63BAPlCEc35cOt+waDqaCqX98+JUtLjI+C4TXJ1w5hAKu5x2eR4dsn2/maKwZIP3acaA9K/weMmBhogrXV2aQJXRQHX+b02iS6nvmnUDNxXzb7CjI7Hf2wioCl92V/hq3WiSpdWYb+I56k/SGsUWSvA8a71Jn0YDhQ1JgxtLpyiP9ZXnjlXajoyKdOiS+9UN4+8mv5PCsnq63Au2QhhMaCB61pEF7YMa6UUeqvWx32ZnaytwKNEeBCIqm413dGA+38JoX9dhithnewV9O/pJ3fhKyF/7ZOp64B7vNpVVuQ8eOYEhDEilaVJgZxFxXWzPmPzXGsRh/HlNJa7kGJ8kRPguJchiGOz03annC8Rb3lbcBvhtVU/t+bv0udc7Zl9csCRd87ieW4SJhwLdnO4cg84XzzOu/CScdZS21wU3Sotjuxg5fXCrOkMplUyl6GCmaRqUX/JP2u2Ai6Xy8AWILgQW4Tqen40GlxpbX+sc369GlBLy/457ao+V1qrqtqbgkyS99gnmMTz/ENLFW9xzGhv9bDV3XgZ6CiFIlYCHUvZqiEXJHMtDiGPyzFOv4JoHMoWMAPlk8t1zoJ1+SO68ko=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
